#ifndef _RANDOMTYPE_H_
#define _RANDOMTYPE_H_

enum RandomType
{
    UNIFORM_RANDOM_GENERATOR = 0,
    NORMAL_RANDOM_GENERATOR,
    EXPONENTIAL_RANDOM_GENERATOR,
    LOGARIFM_RANDOM_GENERATOR,
    JOHNSON_SV_RANDOM_GENERATOR,
    JOHNSON_SU_RANDOM_GENERATOR
};

#endif